### ISSUE TITLE
`cargo test` failing `fallback_session`

### ISSUE THREAD

**Issue by tripleab** [Ruturajn/fetchit#7]
When running `cargo test`, I get the error message:

```
running 3 tests
test tests::xdg_current ... ok
test tests::xdg_session ... ok
test tests::fallback_session ... FAILED

failures:

---- tests::fallback_session stdout ----
thread 'tests::fallback_session' panicked at 'assertion failed: `(left == right)`
  left: `"i3"`,
 right: `"LG3D"`', src/lib.rs:229:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::fallback_session
```

I'm using i3wm, which explains why the call to `get_session_name` is returning i3 for the left of the comparison. However, I don't understand how the `fallback_session` test is supposed to succeed, as no environment variables are set to the value `LG3D`. It seems to me like the `fallback_session` test should be changed on line 221, to set the environment variable `DESKTOP_SESSION` to `LG3D`, in order to test whether `get_session_name` works with the `DESKTOP_SESSION` environment variable. 

For testing the fallback value, the expected fallback should be `Unknown` if I'm not mistaken, however the environment variables aren't being cleared in order to test that (since `get_session_name` still seems to be returning `i3wm`, which seems like a different issue altogether.

Sorry if I'm completely misinterpreting the situation, as I'm not totally sure what the intention is with the tests, hence why I have created an issue rather than fixing the test myself and submitting a pull request. Although with some further info I'm happy to fix this issue and submit a pull request (provided there is an issue at all)

Many thanks again!

**Comment by Ruturajn** [comment]
Hi,
Thanks for pointing this out. Actually, I had written the `fallback_session` test to check whether the value for `_NET_WM_NAME`, is properly extracted from `xprop`, and it so happens that, that value is `LG3D` for `qtile` (since, I am using `qtile`). Hence the statement, `assert_eq!(wm_name, "LG3D");`. So, you are right, this is not a generic test, but just a functionality test, for finding the `_NET_WM_NAME`. I will need to remove it, since, the value for `_NET_WM_NAME`, will be different in various WMs.

The reason I added the detection of `_NET_WM_NAME`, was that some WMs, don't set the `XDG` environment variables, and hence, their names need to be extracted by reading the value for `_NET_WM_NAME`, like `dwm` for example, which was brought to my attention, in this [issue](https://github.com/Ruturajn/fetchit/issues/1).

So, that is the whole story behind the `fallback_session` test, and why I never expected its output to be `Unknown`. If you have any thoughts on this please let me know.

Thanks

**Comment by tripleab** [comment]
Ah ok, thanks for letting me know, I thought I was mistaken but it would be best to check.
